# suppress inspection "UnusedProperty" for whole file
### Argon2
hash.argon2.version=19
hash.argon2.memory=19456
hash.argon2.iterations=2
hash.argon2.length=128
hash.argon2.parallelism=1
hash.argon2.type=id
